/*
----------------------------------------------------------------------
-- - Name          : CustomControllerBase 
-- - Author        : VSU
-- - Description   : Base Class for extending ASPISInvoice 
--
-- Maintenance History:
--
-- Date      Name  Version    Remarks
-- -----------  ----  -------    ---------------------------------------
-- 30-AUG-2017  VSU    1.0      Initial version
----------------------------------------------------------------------
**********************************************************************
*/
public abstract class CustomControllerBase {

}